### ISSUE TITLE
Interoperabililty with epiparameter

### ISSUE THREAD

**Issue by adamkucharski** [epiverse-trace/superspreading#2]
At present, epiparameter does not store values of k (i.e. overdispersion in fitted negative binomial distributions). As `superspreading` develops, need ensure estimated parameters can be stored in consistent way, and library values from `epiparameter` can be pulled in for comparison with estimates, and use of post-processing functions.

**Comment by joshwlambert** [comment]
{epiparameter} now stores parameter estimates of offspring distributions (negative binomial, geometric and poisson). What is the best way to show that {superspreading} and {epiparameter} can be used together? 

A short vignette in which parameter estimates of overdispersion are read in and then used by `superspreading::probability_epidemic()` could be a good start. 

If you agree I'm happy to draft this.

**Comment by adamkucharski** [comment]
Yep, that sounds like good starting point – can easily set k=1 or very large to get geometric and poisson in that function. There's also issue #5 on converting the statistical parameters to more intuitive values, which would be a nice illustration.
