### ISSUE TITLE
Add package design vignette

### ISSUE THREAD

**Issue by joshwlambert** [epiverse-trace/superspreading#28]

**Comment by sbfnk** [comment]
I'm still not 100% clear on what the intended package scope is so I guess this would be good to clarify in a design document. At the moment the main functionality seems to be to calculate summary metrics for outbreaks where the offspring distribution follows a negative binomial distribution (which is very useful) - does it also provide functionality to "estimate [...] individual-level variation the in transmission of infectious diseases from data on secondary cases." as the README suggests, or is it intending to do so in the future?

**Comment by joshwlambert** [comment]
I've added a first draft of the design vignette in the `add_design_vig` branch. Please let me know if this helps to clarify the package scope. 

Your comment on estimation did help me to rethink some of the wording on estimation in the documentation such as the README, as we are not providing any methods to perform inference, I've left as is for now but let me know if you recommend changing it. I'm not opposed to adding some simple fitting functions (using {stats} or {stats4}) if this would be useful for the package's audience.
