### ISSUE TITLE
Alternative fitting to negative binomial

### ISSUE THREAD

**Issue by adamkucharski** [epiverse-trace/superspreading#4]
Functions described here could be explored and compared using `quickfit` functionality: https://www.nature.com/articles/s41598-021-93578-x

**Comment by joshwlambert** [comment]
I've now added functions to calculate the likelihood for a Poisson-lognormal and Poisson-Weibull (as they do in the paper linked in the issue).

However, without documentation these functions will be difficult to use. I think this issue could be addressed in the same vignette as mentioned in #1, including fitting with Pois-lnorm and Pois-Weibull alongside Neg-Binom, Geom and Pois using {fitdistrplus}.

Let me know if you agree.

**Comment by adamkucharski** [comment]
Sounds good. The more complex functions may only be relevant for niche cases, but could be useful to include as 'advanced options' alongside the more traditional ones you mention.
