### ISSUE TITLE
Post-processing to convert R/k into proportion of transmission events

### ISSUE THREAD

**Issue by adamkucharski** [epiverse-trace/superspreading#5]
For applied audiences (e.g. [policy reports](https://www.gov.uk/government/publications/analysis-of-sars-cov-2-transmission-clusters-and-superspreading-events-3-june-2020) ) is often useful to convert R and k estimates into more intuitive metrics, such as:

1.  the proportion of cases that are responsible for X% of transmission (e.g. '10% of SARS-CoV-2 cases cause 80% of transmission)
2. the proportion of new cases that originated with a transmission event of a given size (useful to inform backwards contact tracing efforts, i.e. how many cases are associated with large clusters).

Here is some rough simulation-based code to perform 1:

```
# Estimate what proportion of cases 80% of transmission

x <- 0.8
reproduction_number <- 2
kk_in <- c(0.1,0.2,0.3,0.4,0.5,1)
cluster_size <- 10

store_dat <- data.frame(k=0*kk_in,prop_80=0*kk_in)

for(ii in 1:length(kk_in)){
  
  nn_sim = 1e5
  simulate_secondary = rnbinom(nn_sim,mu=reproduction_number,size=kk_in[ii])

  total_80 = x*sum(simulate_secondary) # 80% of cases
  out_val <-  sum(cumsum(sort(simulate_secondary,decreasing = T )) <= total_80)/nn_sim # What proportion cause them?
  
  # Define cluster - larger than 10 cases
  store_dat[ii,]$k <- kk_in[ii]
  store_dat[ii,]$prop_80 <- paste0(round(100*out_val),"%")
  
}
```

And to perform 2:

```
reproduction_number <- 2
kk_in <- c(0.1,0.2,0.3,0.4,0.5)
cluster_size <- 10

store_dat <- data.frame(k=0*kk_in,
                        prop_5=0*kk_in,
                        prop_10=0*kk_in,
                        prop_20=0*kk_in)

for(ii in 1:length(kk_in)){

  nn_sim = 1e5
  simulate_secondary = rnbinom(nn_sim,mu=reproduction_number,size=kk_in[ii])
  
  propn_cluster_1 <- sum(simulate_secondary[simulate_secondary>=5])/sum(simulate_secondary)
  propn_cluster_2 <- sum(simulate_secondary[simulate_secondary>=10])/sum(simulate_secondary)
  propn_cluster_3 <- sum(simulate_secondary[simulate_secondary>=25])/sum(simulate_secondary)
  
  # Define cluster - larger than 10 cases
  store_dat[ii,]$k <- kk_in[ii]
  store_dat[ii,]$prop_5 <- paste0(signif(100*propn_cluster_1,2),"%")
  store_dat[ii,]$prop_10 <- paste0(signif(100*propn_cluster_2,2),"%")
  store_dat[ii,]$prop_20 <- paste0(signif(100*propn_cluster_3,2),"%")
}
```

**Comment by joshwlambert** [comment]
@adamkucharski for the code chunk to perform 1) it seems that `cluster_size` is assigned and referred to (`# Define cluster - larger than 10 cases`) but does not seem to be used. Is there something missing or case this variable be removed?

**Comment by adamkucharski** [comment]
Good spot – that's been deprecated, as replaced with >=5, >=10, >=20 in table.

**Comment by joshwlambert** [comment]
PR #11 adds two functions that perform that two calculation above. It does not introduced any long-form documentation (i.e. vignettes) describing these. 

I think the use of the policy report (linked to in the first message of this issue) would be a good case study of where these functions have utility and this could become a vignette. This should be tackled in a separate PR focused on this vignette. I will open an issue to log this and can start a discussion there to determine the best content for the vignette.
