### ISSUE TITLE
Analytical minimum to probability of extinction? 

### ISSUE THREAD

**Issue by joshwlambert** [epiverse-trace/superspreading#54]
In the full package review it was asked whether the grid search in `probability_epidemic()` could be replaced by analytically finding the minimum of the function. 

https://github.com/epiverse-trace/superspreading/blob/main/R/probability_epidemic.R#L60

@adamkucharski do you know if this is possible?

**Comment by adamkucharski** [comment]
It's doable for k=1 (s=1-1/R) but not feasible to get analytic solution for other values of k I think (Wolfram Alpha [seemed to agree](https://www.wolframalpha.com/input?i=Solve+for+x%3A+%281%2B%28R%2Fk%29*%281%E2%80%93x%29%29%5E%28%E2%80%93k%29%3Dx))
